import { builtinModules } from "node:module";
import esbuild from "esbuild";
import fs from "fs";
import path from "path";
import process from "process";
import { createCssMergePlugin } from "./scripts/css-merge.mjs";
import {
	BANNER_START,
	buildLicenseBanner,
	collectBundledPackages,
	findUnlistedPackages,
} from "./scripts/license-banner.mjs";
import { UI_RUNTIME_ALIASES } from "./scripts/ui-runtime-aliases.mjs";
import { copyToVault, readVaultPluginPath } from "./scripts/vault-copy.mjs";

const prod = process.argv[2] === "production";
const DIST_DIR = "dist";

const { id: pluginId, version } = JSON.parse(fs.readFileSync("manifest.json", "utf8"));
fs.mkdirSync(DIST_DIR, { recursive: true });

// Plugin to load HTML files as strings for mobile-compatible bundled assets.
const htmlPlugin = {
	name: "html-loader",
	setup(build) {
		build.onLoad({ filter: /\.html$/ }, async (args) => {
			// Bundle HTML files inline for mobile compatibility where runtime file loading doesn't work.
			const html = await fs.promises.readFile(args.path, "utf8");
			return {
				contents: `export default ${JSON.stringify(html)};`,
				loader: "js",
			};
		});
	},
};

// Explicit, non-path-sorted order for first-party CSS source modules (spec §7.17). Foundations
// and shared components load before any view so a view's rules can override a shared default.
const FIRST_PARTY_CSS = [
	"src/styles/foundations/common.css",
	"src/styles/components/settings.css",
	"src/styles/components/quick-preview-modal.css",
	"src/styles/views/swimlane.css",
	"src/styles/views/calendar.css",
	"src/styles/views/timeline.css",
	"src/styles/views/gantt.css",
	"src/styles/views/sticky-note.css",
].map((p) => path.resolve(p));

// Merge first-party sources, imported CSS, and the Gantt Chart stylesheet (which nothing imports)
// into dist/styles.css.
const cssPlugin = createCssMergePlugin({
	stylesPath: `${DIST_DIR}/styles.css`,
	banner: buildLicenseBanner("styles.css"),
	bannerStart: BANNER_START,
	firstPartyCss: FIRST_PARTY_CSS,
	extraCss: [
		{
			path: path.resolve("node_modules/@jaeungkim/gantt-chart/dist/gantt-chart.css"),
			note: "Unmodified; Gantt themes it through --gantt-* tokens in first-party CSS",
		},
	],
});

// Plugin to verify that every bundled npm package is attributed in THIRD_PARTY_NOTICES.md.
// Production builds exit non-zero on a problem; watch mode only warns.
const licenseProblems = [];
const licenseCheckPlugin = {
	name: "license-check",
	setup(build) {
		build.onEnd((result) => {
			licenseProblems.length = 0;
			if (!result.metafile) return;
			const bundled = collectBundledPackages(result.metafile, (dir) =>
				JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8")),
			);
			const notices = fs.readFileSync("THIRD_PARTY_NOTICES.md", "utf8");
			licenseProblems.push(...findUnlistedPackages(bundled, notices));
			for (const problem of licenseProblems) {
				console.error(`✗ License notice: ${problem}`);
			}
		});
	},
};

// Completes dist/ with the manifest. In watch mode it then copies the artifacts into the vault plugin
// folder named by OBSIDIAN_VAULT_PLUGIN_PATH in .env; without that variable the copy is skipped.
// A production build never writes outside the repository (use `pnpm run deploy` for that).
const publishPlugin = {
	name: "publish-artifacts",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) return;
			fs.copyFileSync("manifest.json", `${DIST_DIR}/manifest.json`);
			if (prod) return;

			const pluginDir = readVaultPluginPath();
			if (!pluginDir) {
				console.log("OBSIDIAN_VAULT_PLUGIN_PATH not set; skipping vault copy");
				return;
			}
			try {
				const destination = copyToVault({ distDir: DIST_DIR, pluginDir, pluginId });
				console.log(`✓ Copied build to ${destination}`);
			} catch (error) {
				console.error(`✗ Vault copy failed: ${error.message}`);
			}
		});
	},
};
const banner = `${buildLicenseBanner("main.js", version)}
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const context = await esbuild.context({
	// React-targeting libraries (Gantt) run on Preact; see scripts/ui-runtime-aliases.mjs.
	alias: UI_RUNTIME_ALIASES,
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${DIST_DIR}/main.js`,
	minify: prod,
	metafile: true,
	plugins: [htmlPlugin, cssPlugin, licenseCheckPlugin, publishPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(licenseProblems.length > 0 ? 1 : 0);
} else {
	await context.watch();
}
